version: '3.0'
services:
  dsouidi_binarybodyshaming_fr_fastapi:
    container_name: dsouidi_binarybodyshaming_fr_fastapi

    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root/workspace
    ports:
      - 8999:8999
